name: mir187-imaging
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-image
  - scipy
  - matplotlib
  - jupyter
  - pip
  - pip:
      - tifffile
      - napari[all]
